app:
  port: 8080

db:
  host: localhost
  port: 5432
  username: unflat
  password: unflat
  dbname: auth-db
  sslmode: disable


tools:
  jwt: dfs9jhg3hg6jhg21jhg4jhg
  PasswordSalt: sg2fh1sd2kl6gh3fl4sd3jk4hg9ls